package org.cce.sistema.model;
// Generated 3/07/2020 02:30:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bautismo generated by hbm2java
 */
public class Bautismo  implements java.io.Serializable {


     private Integer idBautismo;
     private String parroquia;
     private String lugar;
     private Set catequizados = new HashSet(0);

    public Bautismo() {
    }

    public Bautismo(String parroquia, String lugar, Set catequizados) {
       this.parroquia = parroquia;
       this.lugar = lugar;
       this.catequizados = catequizados;
    }
   
    public Integer getIdBautismo() {
        return this.idBautismo;
    }
    
    public void setIdBautismo(Integer idBautismo) {
        this.idBautismo = idBautismo;
    }
    public String getParroquia() {
        return this.parroquia;
    }
    
    public void setParroquia(String parroquia) {
        this.parroquia = parroquia;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Set getCatequizados() {
        return this.catequizados;
    }
    
    public void setCatequizados(Set catequizados) {
        this.catequizados = catequizados;
    }




}


