package org.cce.sistema.model;
// Generated 3/07/2020 02:30:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Codigo generated by hbm2java
 */
public class Codigo  implements java.io.Serializable {


     private Integer idCodigo;
     private Integer codigoPostal;
     private String colonia;
     private Set catequistas = new HashSet(0);
     private Set catequizados = new HashSet(0);

    public Codigo() {
    }

    public Codigo(Integer codigoPostal, String colonia, Set catequistas, Set catequizados) {
       this.codigoPostal = codigoPostal;
       this.colonia = colonia;
       this.catequistas = catequistas;
       this.catequizados = catequizados;
    }
   
    public Integer getIdCodigo() {
        return this.idCodigo;
    }
    
    public void setIdCodigo(Integer idCodigo) {
        this.idCodigo = idCodigo;
    }
    public Integer getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public Set getCatequistas() {
        return this.catequistas;
    }
    
    public void setCatequistas(Set catequistas) {
        this.catequistas = catequistas;
    }
    public Set getCatequizados() {
        return this.catequizados;
    }
    
    public void setCatequizados(Set catequizados) {
        this.catequizados = catequizados;
    }




}


