package org.cce.sistema.model;
// Generated 3/07/2020 02:30:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private Integer idMunicipio;
     private String nombre;
     private Set catequistas = new HashSet(0);
     private Set catequizados = new HashSet(0);

    public Municipio() {
    }

    public Municipio(String nombre, Set catequistas, Set catequizados) {
       this.nombre = nombre;
       this.catequistas = catequistas;
       this.catequizados = catequizados;
    }
   
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCatequistas() {
        return this.catequistas;
    }
    
    public void setCatequistas(Set catequistas) {
        this.catequistas = catequistas;
    }
    public Set getCatequizados() {
        return this.catequizados;
    }
    
    public void setCatequizados(Set catequizados) {
        this.catequizados = catequizados;
    }




}


