package org.cce.sistema.model;
// Generated 3/07/2020 02:30:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Numero generated by hbm2java
 */
public class Numero  implements java.io.Serializable {


     private Integer idNumero;
     private Integer numeroCasa;
     private Set catequizados = new HashSet(0);
     private Set catequistas = new HashSet(0);

    public Numero() {
    }

    public Numero(Integer numeroCasa, Set catequizados, Set catequistas) {
       this.numeroCasa = numeroCasa;
       this.catequizados = catequizados;
       this.catequistas = catequistas;
    }
   
    public Integer getIdNumero() {
        return this.idNumero;
    }
    
    public void setIdNumero(Integer idNumero) {
        this.idNumero = idNumero;
    }
    public Integer getNumeroCasa() {
        return this.numeroCasa;
    }
    
    public void setNumeroCasa(Integer numeroCasa) {
        this.numeroCasa = numeroCasa;
    }
    public Set getCatequizados() {
        return this.catequizados;
    }
    
    public void setCatequizados(Set catequizados) {
        this.catequizados = catequizados;
    }
    public Set getCatequistas() {
        return this.catequistas;
    }
    
    public void setCatequistas(Set catequistas) {
        this.catequistas = catequistas;
    }




}


