package org.cce.sistema.model;
// Generated 14/07/2020 11:18:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Parroquia generated by hbm2java
 */
public class Parroquia  implements java.io.Serializable {


     private Integer idParroquia;
     private String lugar;
     private int idParroquia_1;
     private Set catequizados = new HashSet(0);

    public Parroquia() {
    }

	
    public Parroquia(int idParroquia_1) {
        this.idParroquia_1 = idParroquia_1;
    }
    public Parroquia(String lugar, int idParroquia_1, Set catequizados) {
       this.lugar = lugar;
       this.idParroquia_1 = idParroquia_1;
       this.catequizados = catequizados;
    }
   
    public Integer getIdParroquia() {
        return this.idParroquia;
    }
    
    public void setIdParroquia(Integer idParroquia) {
        this.idParroquia = idParroquia;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public int getIdParroquia_1() {
        return this.idParroquia_1;
    }
    
    public void setIdParroquia_1(int idParroquia_1) {
        this.idParroquia_1 = idParroquia_1;
    }
    public Set getCatequizados() {
        return this.catequizados;
    }
    
    public void setCatequizados(Set catequizados) {
        this.catequizados = catequizados;
    }




}


